version: '3.9'

services:
    app:
        build:
            context: .
            target: test
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=test
        volumes:
            - ./coverage:/project/coverage
