version: '3.9'

services:
    app:
        build:
            context: .
            target: development
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
            - PORT=3000

        ports:
            - '3000:3000'
        volumes:
            - ./coverage:/project/coverage
