version: '3.9'

services:
    app:
        build:
            context: .
            target: production
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
        volumes:
            - ./coverage:/project/coverage
